@startuml MII_MTB_Overview
object MII Onkologie
object MII Pathologischer Befundbericht
object MII Molekulargenetischer Befundbericht
object MII Molekulares Tumorboard
object IHC-Befund
object ISH-Befund

object FISH-Befund
object Diagnose
object Vortherapie 
object MTB_Systemische_Therapie
object 
@enduml