@startuml MII_MTB_LM
skinparam Linetype ortho
skinparam Nodesep 150
skinparam Ranksep 80
skinparam legendBackgroundColor #white

package EpisodeOfCare {
    class MTB_EpisodeOfCare {
        + Anmeldedatum: Datum
        + MTB_Einwilligung: MTB_Einwilligung
        + Diagnose: Diagnose
        + Vortherapie: Vortherapie
        + ECOG: ECOG
        + Probe: Probe
        + Molekular_Pathologie_Befund: Molekular_Pathologie_Befund
        + NGS_Bericht: NGS_Bericht
        + MTB_Beschluss_Therapieplan: MTB_Beschluss_Therapieplan
    }

    class MTB_Einwilligung {
        + Status: Kode
    }

    class Diagnose {
        + Leitlinienbehandlung_Status: Kode
        + WHO_Grad_ZNS: Kode
        + Tumorausbreitung_ED_Wert: Kode
        + Tumorausbreitung_ED_Zeitpunkt: Datum
        + Tumorausbreitung_MTB_Wert: Kode
        + Tumorausbreitung_MTB_Zeitpunkt: Datum
    }

    class Vortherapie {
        + Zulassungsstatus: Kode
        + Therapielinie: Zähler
        + Startdatum: Datum
        + Enddatum: Datum
        + Wirkstoffe: Zeichenkette
        + Systematische_Therapie_Ende_Grund: Kode
        + Typ_Kategorie: Zeichenkette
    }

    class ECOG {
        + Datum: Datum
    }

    class Probe {
        + Tumorzellgehalt_Methode: Kode
        + Tumorzellgehalt_Wert: Dezimalzahl
    }

    package MolekularPathologieBefund {
        class Molekular_Pathologie_Befund {
            + Art_Diagnostik: Kode
            + IHC_Befund: IHC_Befund
            + ISH_Befund: ISH_Befund
        }

        class IHC_Befund {
            + Erstellungsdatum: Datum
            + Block_Material_Nr: Zeichenkette
            + Klon: Zeichenkette
        }

        class Protein_Befunde {
            + Protein: Kode
            + Ergebnis: IHC_Ergebnis
        }

        class IHC_Ergebnis {
            + Ergebnis: Kode
            + Prozent: Dezimalzahl
            + Score: Kode
            + TPS_Score: Dezimalzahl
            + CPS_Score: Dezimalzahl
            + IC_Score: Dezimalzahl
            + TC_Score: Dezimalzahl
            + Interpretation: Zeichenkette
            + MSI_MMR: MSI_MMR_Ergebnis
        }

        class MSI_MMR_Ergebnis {
            + Wert: Kode
            + Interpretation: Zeichenkette
        }

        class ISH_Befund {
            + Erstellungsdatum: Datum
            + Block_Material_Nr: Zeichenkette
            + Gen_Sonde: Zeichenkette
            + Wert: Dezimalzahl
            + Ergebnis: ISH_Ergebnis
        }

        class ISH_Ergebnis {
            + Wert: Kode
            + Interpration: Zeichenkette
        }
    }

    package NGSBericht {
        class NGS_Bericht {
            + Erstellungsdatum: Datum
            + NGS_QC: NGS_QC
            + NGS_Metadaten: NGS_Metadaten
            + TMB: TMB
            + HRD_Score: HRD_Score
            + BRCAness: BRCAness
            + MSI: MSI
            + Einfache_Variante: Einfache_Variante
            + RNA_Seq: RNA_Seq
            + RNA_Fusion: RNA_Fusion
            + CNV: Copy_Number_Variante
        }

        package NGSMetadaten {

            class NGS_QC {
                + Sequencing_Read_Type: Zeichenkette
                + Lueckenstatistik: Dezimalzahl
                + Read_Laenge: Zähler
            }

            class NGS_Metadaten {
                + Fragmentierung: Zeichenkette
                + Sequenzierkit: Sequenzierkit
                + Librarykit_Praeperationskit: Library_Praeperationskit
                + Sequenziergeraet: Sequenziergeraet
                + Art_Sequenzierung: Kode
                + Erstellungsdatum: Datum
                + Referenzgenom: Zeichenkette
                + Probe: Probe
                + Pipeline: Zeichenkette
            }

            class Sequenzierkit {
                Hersteller: Zeichenkette
                Bezeichnung: Zeichenkette
            }

            class Library_Praeperationskit {
                Hersteller: Zeichenkette
                Bezeichnung: Zeichenkette
            }

            class Sequenziergeraet {
                Modell: Zeichenkette
                Hersteller: Zeichenkette
            }
        }

        class Gen_Kodierung{
            + ENSEMBL_ID: Zeichenkette
            + HGNC_ID: Zeichenkette
            + Symbol: Zeichenkette
            + Name_Gen: Zeichenkette
        }

        package KomplexeBiomarker {
            class TMB {
                Wert: Dezimalzahl
                Interpretation: Zeichenkette
            }

            class HRD_Score {
                Wert: Dezimalzahl
                Interpretation: Zeichenkette
            }

            class BRCAness {
                Wert: Dezimalzahl
                Interpretation: Zeichenkette
            }

            class MSI {
                Wert: Dezimalzahl
                Interpretation: Zeichenkette
            }
        }

        class Positionsbereich {
            + Start: Zähler
            + Ende: Zähler
        } 

        class Einfache_Variante {
            + Gen: Gen_Kodierung
            + Positionsbereich: Positionsbereich
            + Interpretation: Zeichenkette
        }

        class RNA_Seq {
            + Transcripts_Per_Million: Dezimalzahl
            + Cohort_Ranking: Zähler
            + Library_size: Zähler
            + Raw_counts: Zähler
            + Tissue_Corrected_Expression: Bool
            + Transcript_ID: Zeichenkette
            + Gen: Zeichenkette
            + Ensemble_ID: Zeichenkette
            + Entrez_ID: Zeichenkette
            + Varianten_ID: Zeichenkette
        }

        package StrukturelleVeraenderungen {
            class RNA_Fusion {
                + RNA_Fusion_Partner: RNA_Fusion_Partner
                + Number_Reported_Reads: Zähler
                + COSMIC_ID: Zeichenkette
                + Effect: Zeichenkette
                + 3'FusionPartner: Zeichenkette
                + 5'FusionPartner: Zeichenkette
                + Varianten_ID: Zeichenkette
            }

            class RNA_Fusion_Partner {
                + RNA_Fusion_Partner_Strand: Kode
                + RNA_Fusion_Partner_Transcript_Position: Zähler
                + RNA_Fusion_Partner_Exon_ID: Zeichenkette
                + RNA_Fusion_Partner_Transcript_ID: Zeichenkette
                + RNA_Fusion_Partner_Gen: Zeichenkette
            }

            class DNA_Fusion {
                + DNA_Fusion_Partner: DNA_Fusion_Partner
                + Number_reported_reads: Zähler
                + 3'Domain: Zeichenkette
                + 5'Domain: Zeichenkette
                + Varianten_ID: Zeichenkette
            }

            class DNA_Fusion_Partner {
                + Fusion_Partner_Chromosom: Zeichenkette
                + Fusion_Partner_Position: Zähler
                + Fusion_Partner_Gen: Zähler
            }

            class Copy_Number_Variante {
                + Positionsbereich: Positionsbereich
                + Copy_Number_Neutral_LoH: Zeichenkette
                + Type: Zeichenkette
                + Reported_Focality: Zeichenkette
                + Reported_Affected_Genes: Gen_Kodierung
                + CNB: Zeichenkette
                + CNA: Zeichenkette
                + Relative_CN: Dezimalzahl
                + Total_CN: Zähler
                + Chromosom: Zeichenkette
                + Varianten_ID: Zeichenkette

            } 
            
            class Ploidie {
                + Kopienanzahl: Zähler
            }
        }

    }

    package MTBBeschlussTherapieplan {
        class MTB_Beschluss_Therapieplan {
            + Erstellungsdatum: Datum
            + Protokollauszug: Zeichenkette
            + Status_Begründung: Zeichenkette
            + Therapie_Empfehlung: Therapie_Empfehlung
            + Rebiopsie_Auftrag: Zeichenkette
            + Humangenetische_Beratung_Auftrag: Humagenetische_Beratung_Auftrag
            + Histologie_Reevaluation_Auftrag: Histologie_Reevaluation_Auftrag
        }

        class Therapie_Empfehlung {
            + Stützende_Molekulare_Alterationen: Zeichenkette
            + Stützende_Entität: Zeichenkette
            + Evidenz_Level: Evidenz_Level
            + Wirkstoffe: Zeichenkette
            + Priorität: Kode
            + Studien_Einschluss_Empfehlung: Studien_Einschluss_Empfehlung
        }

        class Evidenz_Level {
            + Graduierung: Kode
            + Zusatz: Zeichenkette
            + Publikation: Publikation
        }

        class Publikation {
            + Digital_class_Identifier: Zeichenkette
            + Pub_Med_Identifier: Zeichenkette
        }

        class Studien_Einschluss_Empfehlung{
            + Stützende_Entität: Zeichenkette
            + NCT_Nummer: Zeichenkette
            + Eudra_CT_Cummer: Zeichenkette
            + DRKS_Nummer: Zeichenkette
        }

        class Rebiopsie_Auftrag {
            + Begründung: Zeichenkette
        }

        class Humagenetische_Beratung_Auftrag {
            + Begründung: Zeichenkette
        }

        class Histologie_Reevaluation_Auftrag {
            + Begründung: Zeichenkette
        }
    }
}

package FollowUp {
    class MTB_Followup {
        + Erfassungsdatum: Datum
        + Follow_up_Status: Kode
        + Grund_Nicht_Umsetzung: Kode
        + Systemische_Therapie: Kode
    }

    class MTB_Systemische_Therapie {
        + Therapie_Startdatum: Datum
        + Therapie_Enddatum: Datum
        + Systemische_Therapie_Ende_Grund: Kode
        + Therapie_Empfehlung: Zeichenkette
        + Bemerkungen : Zeichenkette
        + Status: Kode
        + Wirkstoffe: Zeichenkette
        + Dosisdichte: Kode
        + Response_Befund: Response_Befund
    }

    class Response_Befund {
        + Response_Beurteilung: Kode
        + Beurteilungsmethode: Kode
        + Zeitpunkt: Datum
    }


    class MTB_Antrag_Kostenuebernahme {
        + Ausstellungsdatum: Datum
        + Therapieempfehlung: Zeichenkette
        + Antragsstadium: Kode
        + Antragstellung_ZPM_Geschaeftstelle: Zeichenkette
    }

    class MTB_Antwort_Kostenuebernahme {
        + Datum: Datum
        + Antrag: Zeichenkette
        + Status: Kode
        + Grund: Kode
    }
}


MTB_EpisodeOfCare o-u- MTB_Einwilligung
MTB_EpisodeOfCare o-u- Diagnose
MTB_EpisodeOfCare o-l- Vortherapie
MTB_EpisodeOfCare o-u- ECOG
MTB_EpisodeOfCare o-r- Probe
MTB_EpisodeOfCare o-- Molekular_Pathologie_Befund
MTB_EpisodeOfCare o-d- NGS_Bericht
MTB_EpisodeOfCare o-l- MTB_Beschluss_Therapieplan

Molekular_Pathologie_Befund o-- IHC_Befund
IHC_Befund o-- Protein_Befunde
Protein_Befunde o-- IHC_Ergebnis
IHC_Ergebnis o-- MSI_MMR_Ergebnis
Molekular_Pathologie_Befund o-- ISH_Befund
ISH_Befund o-- ISH_Ergebnis


NGS_Bericht o-u- NGS_QC
NGS_Bericht o-- NGS_Metadaten
NGS_Bericht o-- Einfache_Variante
NGS_Bericht o-- RNA_Seq
NGS_Bericht o-- RNA_Fusion
NGS_Bericht o-u- TMB
NGS_Bericht o-u- HRD_Score
NGS_Bericht o-u- BRCAness
NGS_Bericht o-u- MSI
NGS_Bericht o-- Copy_Number_Variante
NGS_Bericht o-- Ploidie
NGS_Bericht o-- DNA_Fusion
RNA_Fusion o-- RNA_Fusion_Partner
DNA_Fusion o-- DNA_Fusion_Partner
NGS_Metadaten o-- Sequenzierkit
NGS_Metadaten o-- Library_Praeperationskit
NGS_Metadaten o-- Sequenziergeraet
Einfache_Variante o-d- Positionsbereich
Copy_Number_Variante o-l- Positionsbereich
Einfache_Variante o-- Gen_Kodierung
Copy_Number_Variante o-- Gen_Kodierung

MTB_Beschluss_Therapieplan o-- Therapie_Empfehlung
Therapie_Empfehlung o-- Evidenz_Level
Evidenz_Level o-- Publikation
Therapie_Empfehlung o-- Studien_Einschluss_Empfehlung
MTB_Beschluss_Therapieplan o-- Rebiopsie_Auftrag
MTB_Beschluss_Therapieplan o-- Humagenetische_Beratung_Auftrag
MTB_Beschluss_Therapieplan o-- Histologie_Reevaluation_Auftrag

MTB_Followup o-- MTB_Systemische_Therapie
MTB_Systemische_Therapie o-- Response_Befund
MTB_Followup o-- MTB_Antrag_Kostenuebernahme
MTB_Followup o-- MTB_Antwort_Kostenuebernahme

Ploidie -[hidden]- Copy_Number_Variante
DNA_Fusion_Partner -[hidden]- Copy_Number_Variante
RNA_Seq -[hidden]- Einfache_Variante
NGS_QC -[hidden]- Sequenziergeraet
FollowUp -[hidden]r- MolekularPathologieBefund
FollowUp -[hidden]l- MTB_Beschluss_Therapieplan
FollowUp -[hidden]d- MolekularPathologieBefund
Gen_Kodierung -[hidden]u- Positionsbereich
@enduml