RuleSet: RNASeq
* RNASeq                                 0..*   BackboneElement         "RNA Fusion"
  * VariantenId                          0..1   string                  "Varianten ID"
  * EntrezID                             0..1   string                  "Entrez ID"
  * EnsembleID                           0..1   string                  "Ensemble ID"
  * Gen                                  0..1   Reference               "Gen"
  * TranscriptID                         0..1   integer                 "Transcript ID"
  * TranscriptsPerMillion                0..1   decimal                 "Transcripts Per Million"
  * TissueCorrectedExpression            0..1   boolean                 "Tissue Corrected Expression"
  * RawCounts                            0..1   integer                 "Raw counts"
  * LibrarySize                          0..1   integer                 "Library size"
  * CohortRanking                       0..1   integer                 "Cohort ranking"

RuleSet: RNASeqMapping
* RNASeq                            ->      ""
  * VariantenId                     ->      ""
  * EntrezID                        ->      ""
  * EnsembleID                      ->      ""
  * Gen                             ->      ""
  * TranscriptID                    ->      ""
  * TranscriptsPerMillion           ->      ""
  * TissueCorrectedExpression       ->      ""
  * RawCounts                       ->      ""
  * LibrarySize                     ->      ""
  * CohortRanking                  ->      ""