RuleSet: RNASeq
* RNASeq                                 0..*   BackboneElement         "RNA Fusion"
  * VariantenId                          0..1   string                  "Varianten ID"
  * EntrezID                             0..1   string                  "Entrez ID"
  * EnsembleID                           0..1   string                  "Ensemble ID"
  * Gen                                  0..1   Reference               "Gen"
  * TranscriptID                         0..1   integer                 "Transcript ID"
  * TranscriptsPerMillion                0..1   decimal                 "Transcripts Per Million"
  * TissueCorrectedExpression            0..1   boolean                 "Tissue Corrected Expression"
  * RawCounts                            0..1   integer                 "Raw counts"
  * LibrarySize                          0..1   integer                 "Library size"
  * CohortRanking                       0..1   integer                 "Cohort ranking"

RuleSet: RNASeqMapping
* RNASeq                            ->      "MII_PR_MTB_RNA_Seq"
  * VariantenId                     ->      "MII_PR_MTB_RNA_Seq.component[variation-code]"
  * EntrezID                        ->      "MII_PR_MTB_RNA_Seq.component[variation-code]"
  * EnsembleID                      ->      "MII_PR_MTB_RNA_Seq.component[variation-code]"
  * Gen                             ->      "MII_PR_MTB_RNA_Seq.component[gene-studied]"
  * TranscriptID                    ->      "MII_PR_MTB_RNA_Seq.component[transcript-id]"
  * TranscriptsPerMillion           ->      "MII_PR_MTB_RNA_Seq.component[transcripts-per-million]"
  * TissueCorrectedExpression       ->      "MII_PR_MTB_RNA_Seq.component[tissue-corrected-expression]"
  * RawCounts                       ->      "MII_PR_MTB_RNA_Seq.component[raw-counts]"
  * LibrarySize                     ->      "MII_PR_MTB_RNA_Seq.component[library-size]"
  * CohortRanking                   ->      "MII_PR_MTB_RNA_Seq.component[cohort-ranking]"