// dnpm-lm-ngs-report.fsh
// Standalone Logical Model for the DNPM DIP NGS Report JSON structure.
// Covers all fields under ngsReports[] including deeply nested results
// (tumorCellContent, TMB, BRCAness, HRDScore, simpleVariants, copyNumberVariants,
//  dnaFusions, rnaFusions).

Logical: DNPM_LM_NGSReport
Parent: Element
Id: dnpm-lm-ngs-report
Title: "DNPM NGS Report"
Description: "Logical Model for a single entry in the DNPM DIP MTB Patient Record ngsReports array"
* ^url = "https://dnpm-dip.net/fhir/StructureDefinition/dnpm-lm-ngs-report"
* ^status = #active

* dnpmId 1..1 string "NGS Report UUID (DNPM internal ID)"

* patient 1..1 BackboneElement "Patient reference"
  * id 1..1 string "Patient ID"
  * type 1..1 string "Reference type (Patient)"

* specimen 1..1 BackboneElement "Tumor specimen reference"
  * id 1..1 string "Specimen ID"
  * type 1..1 string "Reference type (TumorSpecimen)"

* issuedOn 1..1 string "Report issue date (YYYY-MM-DD)"

* type 1..1 BackboneElement "NGS analysis type (e.g. exome, panel)"
  * code 1..1 string "Type code"
  * display 0..1 string "Type display"
  * system 1..1 string "Type system URI"

// ---- Metadata ----
* metadata 0..1 BackboneElement "NGS run metadata"
  * referenceGenome 0..1 BackboneElement "Reference genome used"
    * code 1..1 string "Genome build code (e.g. GRCh38)"
    * display 0..1 string "Genome build display"
    * system 1..1 string "Genome build system URI"
  * sequencer 0..1 BackboneElement "Sequencer instrument"
    * code 1..1 string "Sequencer code"
    * display 0..1 string "Sequencer display"
    * system 1..1 string "Sequencer system URI"
  * kitManufacturer 0..1 string "Kit manufacturer name"
  * kitType 0..1 string "Kit type name"
  * pipeline 0..1 string "Bioinformatics pipeline identifier"
  * tumorCellContent 0..1 BackboneElement "Tumor cell content metadata estimate"
    * method 0..1 BackboneElement "Estimation method"
      * code 1..1 string "Method code"
      * display 0..1 string "Method display"
      * system 1..1 string "Method system URI"
    * value 1..1 decimal "Tumor cell content fraction (0.0 – 1.0)"

// ---- Results ----
* results 1..1 BackboneElement "NGS analysis results"

  // Tumor cell content (bioinformatic)
  * tumorCellContent 0..1 BackboneElement "Bioinformatically determined tumor cell content"
    * id 1..1 string "Result ID"
    * patient 1..1 BackboneElement "Patient reference"
      * id 1..1 string "Patient ID"
      * type 1..1 string "Reference type"
    * specimen 1..1 BackboneElement "Specimen reference"
      * id 1..1 string "Specimen ID"
      * type 1..1 string "Reference type"
    * method 1..1 BackboneElement "Determination method"
      * code 1..1 string "Method code"
      * display 0..1 string "Method display"
      * system 1..1 string "Method system URI"
    * value 1..1 decimal "Tumor cell content fraction (0.0 – 1.0)"

  // Tumor mutational burden
  * tmb 0..1 BackboneElement "Tumor Mutational Burden"
    * id 1..1 string "TMB result ID"
    * patient 1..1 BackboneElement "Patient reference"
      * id 1..1 string "Patient ID"
      * type 1..1 string "Reference type"
    * specimen 1..1 BackboneElement "Specimen reference"
      * id 1..1 string "Specimen ID"
      * type 1..1 string "Reference type"
    * value 1..1 BackboneElement "TMB quantity"
      * value 1..1 decimal "Numeric TMB value"
      * unit 1..1 string "Unit (e.g. Mutations per megabase)"
    * interpretation 0..1 BackboneElement "TMB interpretation"
      * code 1..1 string "Interpretation code (e.g. high)"
      * display 0..1 string "Interpretation display"
      * system 1..1 string "Interpretation system URI"

  // BRCAness
  * brcaness 0..1 BackboneElement "BRCAness score"
    * id 1..1 string "BRCAness result ID"
    * patient 1..1 BackboneElement "Patient reference"
      * id 1..1 string "Patient ID"
      * type 1..1 string "Reference type"
    * specimen 1..1 BackboneElement "Specimen reference"
      * id 1..1 string "Specimen ID"
      * type 1..1 string "Reference type"
    * value 1..1 decimal "BRCAness score (0.0 – 1.0)"
    * confidenceRange 0..1 BackboneElement "Confidence range"
      * min 1..1 decimal "Minimum confidence value"
      * max 1..1 decimal "Maximum confidence value"

  // HRD Score
  * hrdScore 0..1 BackboneElement "Homologous Recombination Deficiency Score"
    * id 1..1 string "HRD result ID"
    * patient 1..1 BackboneElement "Patient reference"
      * id 1..1 string "Patient ID"
      * type 1..1 string "Reference type"
    * specimen 1..1 BackboneElement "Specimen reference"
      * id 1..1 string "Specimen ID"
      * type 1..1 string "Reference type"
    * value 1..1 decimal "HRD composite score"
    * components 0..1 BackboneElement "HRD component scores"
      * lst 0..1 decimal "Large-scale state transitions (LST)"
      * loh 0..1 decimal "Loss of heterozygosity (LOH)"
      * tai 0..1 decimal "Telomeric allelic imbalance (TAI)"
    * interpretation 0..1 BackboneElement "HRD interpretation"
      * code 1..1 string "Interpretation code (e.g. low)"
      * display 0..1 string "Interpretation display"
      * system 1..1 string "Interpretation system URI"

  // Simple Variants (SNVs / small indels)
  * simpleVariants 0..* BackboneElement "Simple variants (SNV / small indels)"
    * id 1..1 string "Variant ID"
    * patient 1..1 BackboneElement "Patient reference"
      * id 1..1 string "Patient ID"
      * type 1..1 string "Reference type"
    * externalIds 0..* BackboneElement "External variant identifiers (e.g. dbSNP rs-number)"
      * value 1..1 string "Identifier value"
      * system 1..1 string "Identifier system URI"
    * chromosome 1..1 string "Chromosome (e.g. chr4)"
    * gene 1..1 BackboneElement "Affected gene"
      * code 1..1 string "HGNC gene code"
      * display 0..1 string "Gene symbol"
      * system 1..1 string "Gene nomenclature system URI"
    * localization 0..* BackboneElement "Variant localisation in gene"
      * code 1..1 string "Localisation code"
      * display 0..1 string "Localisation display"
      * system 1..1 string "Localisation system URI"
    * transcriptId 0..1 BackboneElement "Transcript identifier"
      * value 1..1 string "Transcript ID value (e.g. ENST...)"
      * system 1..1 string "Transcript system URI"
    * exonId 0..1 string "Exon identifier"
    * position 0..1 BackboneElement "Genomic position (1-based)"
      * start 1..1 integer "Start position"
      * end 0..1 integer "End position"
    * altAllele 1..1 string "Alternate allele"
    * refAllele 1..1 string "Reference allele"
    * dnaChange 0..1 string "cDNA / DNA change in HGVS notation (e.g. c.570G>T)"
    * proteinChange 0..1 string "Protein change in HGVS notation (e.g. p.(Glu125Asp))"
    * readDepth 0..1 integer "Read depth at variant position"
    * allelicFrequency 0..1 decimal "Variant allelic frequency"
    * interpretation 0..1 BackboneElement "ClinVar / clinical interpretation"
      * code 1..1 string "Interpretation code"
      * display 0..1 string "Interpretation display"
      * system 1..1 string "Interpretation system URI"

  // Copy Number Variants
  * copyNumberVariants 0..* BackboneElement "Copy number variants (CNV)"
    * id 1..1 string "CNV ID"
    * patient 1..1 BackboneElement "Patient reference"
      * id 1..1 string "Patient ID"
      * type 1..1 string "Reference type"
    * chromosome 1..1 string "Chromosome (e.g. chr7)"
    * localization 0..* BackboneElement "CNV localisation"
      * code 1..1 string "Localisation code"
      * display 0..1 string "Localisation display"
      * system 1..1 string "Localisation system URI"
    * startRange 0..1 BackboneElement "Start position range"
      * start 1..1 integer "Range start"
      * end 1..1 integer "Range end"
    * endRange 0..1 BackboneElement "End position range"
      * start 1..1 integer "Range start"
      * end 1..1 integer "Range end"
    * totalCopyNumber 0..1 integer "Total copy number"
    * relativeCopyNumber 0..1 decimal "Relative copy number"
    * cnA 0..1 integer "Copy number allele A"
    * cnB 0..1 integer "Copy number allele B"
    * reportedAffectedGenes 0..* BackboneElement "Reported affected genes"
      * code 1..1 string "HGNC gene code"
      * display 0..1 string "Gene symbol"
      * system 1..1 string "Gene nomenclature system URI"
    * focality 0..1 BackboneElement "CNV focality"
      * code 1..1 string "Focality code (e.g. focal)"
      * display 0..1 string "Focality display"
      * system 1..1 string "Focality system URI"
    * type 1..1 BackboneElement "CNV type (gain / loss)"
      * code 1..1 string "CNV type code"
      * display 0..1 string "CNV type display"
      * system 1..1 string "CNV type system URI"

  // DNA Fusions
  * dnaFusions 0..* BackboneElement "DNA-level gene fusions"
    * id 1..1 string "DNA fusion ID"
    * patient 1..1 BackboneElement "Patient reference"
      * id 1..1 string "Patient ID"
      * type 1..1 string "Reference type"
    * localization 0..* BackboneElement "Fusion localisation"
      * code 1..1 string "Localisation code"
      * display 0..1 string "Localisation display"
      * system 1..1 string "Localisation system URI"
    * fusionPartner5prime 0..1 BackboneElement "5-prime fusion partner"
      * gene 1..1 BackboneElement "5-prime partner gene"
        * code 1..1 string "HGNC gene code"
        * display 0..1 string "Gene symbol"
        * system 1..1 string "Gene nomenclature system URI"
      * position 1..1 integer "Breakpoint position"
    * fusionPartner3prime 0..1 BackboneElement "3-prime fusion partner"
      * gene 1..1 BackboneElement "3-prime partner gene"
        * code 1..1 string "HGNC gene code"
        * display 0..1 string "Gene symbol"
        * system 1..1 string "Gene nomenclature system URI"
      * position 1..1 integer "Breakpoint position"
    * reportedNumReads 0..1 integer "Number of reads supporting fusion"

  // RNA Fusions
  * rnaFusions 0..* BackboneElement "RNA-level gene fusions"
    * id 1..1 string "RNA fusion ID"
    * patient 1..1 BackboneElement "Patient reference"
      * id 1..1 string "Patient ID"
      * type 1..1 string "Reference type"
    * externalIds 0..* BackboneElement "External identifiers (e.g. COSMIC fusion ID)"
      * value 1..1 string "Identifier value"
      * system 1..1 string "Identifier system URI"
    * localization 0..* BackboneElement "Fusion localisation"
      * code 1..1 string "Localisation code"
      * display 0..1 string "Localisation display"
      * system 1..1 string "Localisation system URI"
    * fusionPartner5prime 0..1 BackboneElement "5-prime fusion partner"
      * gene 1..1 BackboneElement "5-prime partner gene"
        * code 1..1 string "HGNC gene code"
        * display 0..1 string "Gene symbol"
        * system 1..1 string "Gene nomenclature system URI"
      * transcript 0..1 BackboneElement "5-prime transcript"
        * value 1..1 string "Transcript ID (e.g. ENST...)"
        * system 1..1 string "Transcript system URI"
      * exon 0..1 string "Exon identifier"
      * position 1..1 integer "Breakpoint position"
      * strand 0..1 string "Strand (+ or -)"
    * fusionPartner3prime 0..1 BackboneElement "3-prime fusion partner"
      * gene 1..1 BackboneElement "3-prime partner gene"
        * code 1..1 string "HGNC gene code"
        * display 0..1 string "Gene symbol"
        * system 1..1 string "Gene nomenclature system URI"
      * transcript 0..1 BackboneElement "3-prime transcript"
        * value 1..1 string "Transcript ID (e.g. ENST...)"
        * system 1..1 string "Transcript system URI"
      * exon 0..1 string "Exon identifier"
      * position 1..1 integer "Breakpoint position"
      * strand 0..1 string "Strand (+ or -)"
    * effect 0..1 BackboneElement "RNA fusion effect"
      * code 1..1 string "Effect code (e.g. in-frame)"
      * display 0..1 string "Effect display"
      * system 1..1 string "Effect system URI"
    * reportedNumReads 0..1 integer "Number of reads supporting fusion"
