// dnpm-lm-patient-record.fsh
// Root Logical Model for the DNPM DIP MTB Patient Record JSON structure.
// Models all 19 top-level keys returned by the DNPM API endpoint
// https://dnpm-dip.net/api/mtb/fake/data/patient-record
// Complex sub-structures for ngsReports and carePlans are described in their own
// dedicated files (dnpm-lm-ngs-report.fsh / dnpm-lm-care-plan.fsh); the
// corresponding arrays here carry the same field set inline so that a single
// StructureMap source can navigate the full record without cross-file references.

Logical: DNPM_LM_PatientRecord
Parent: Element
Id: dnpm-lm-patient-record
Title: "DNPM Patient Record"
Description: "Logical Model for the DNPM DIP MTB Patient Record JSON structure (all 19 top-level keys)"
* ^url = "https://dnpm-dip.net/fhir/StructureDefinition/dnpm-lm-patient-record"
* ^status = #active

// =============================================================================
// 1. patient
// =============================================================================
* patient 1..1 BackboneElement "Patient demographics"
  * id 1..1 string "Patient UUID"
  * gender 1..1 BackboneElement "Patient gender"
    * code 1..1 string "Gender code (e.g. female)"
    * display 0..1 string "Gender display text"
    * system 1..1 string "Gender code system"
  * birthDate 1..1 string "Date of birth (YYYY-MM)"
  * healthInsurance 0..1 BackboneElement "Health insurance information"
    * type 1..1 BackboneElement "Insurance type coding"
      * code 1..1 string "Insurance type code (e.g. GKV)"
      * display 0..1 string "Insurance type display"
      * system 1..1 string "Insurance type system URI"
    * reference 0..1 BackboneElement "Insurance provider reference"
      * id 1..1 string "Insurance provider ID"
      * type 1..1 string "Reference type (HealthInsurance)"
      * display 0..1 string "Insurance provider display name"
      * system 0..1 string "Insurance provider system URI"
  * address 0..1 BackboneElement "Patient address (municipality)"
    * municipalityCode 0..1 string "AGS municipality code (5-digit)"
  * age 0..1 BackboneElement "Calculated patient age"
    * value 1..1 integer "Age numeric value"
    * unit 1..1 string "Age unit (e.g. Years)"
  * vitalStatus 1..1 BackboneElement "Vital status"
    * code 1..1 string "Vital status code (e.g. alive)"
    * display 0..1 string "Vital status display"
    * system 1..1 string "Vital status system URI"

// =============================================================================
// 2. episodesOfCare
// =============================================================================
* episodesOfCare 0..* BackboneElement "MTB episodes of care"
  * id 1..1 string "Episode UUID"
  * patient 1..1 BackboneElement "Patient reference"
    * id 1..1 string "Patient ID"
    * type 1..1 string "Reference type (Patient)"
  * period 0..1 BackboneElement "Episode period"
    * start 1..1 string "Start date (YYYY-MM-DD)"
    * end 0..1 string "End date (YYYY-MM-DD)"
  * diagnoses 0..* BackboneElement "Diagnosis references within this episode"
    * id 1..1 string "Diagnosis ID"
    * type 1..1 string "Reference type (MTBDiagnosis)"

// =============================================================================
// 3. diagnoses
// =============================================================================
* diagnoses 0..* BackboneElement "MTB tumor diagnoses"
  * id 1..1 string "Diagnosis UUID"
  * patient 1..1 BackboneElement "Patient reference"
    * id 1..1 string "Patient ID"
    * type 1..1 string "Reference type (Patient)"
  * recordedOn 0..1 string "Date diagnosis was recorded (YYYY-MM-DD)"
  * type 0..1 BackboneElement "Diagnosis type history (main / secondary)"
    * history 0..* BackboneElement "History entries for diagnosis type"
      * date 0..1 string "Entry date"
      * value 0..1 BackboneElement "Diagnosis type value"
        * code 1..1 string "Type code (e.g. main)"
        * display 0..1 string "Type display"
        * system 1..1 string "Type system URI"
  * code 1..1 BackboneElement "ICD-10-GM tumor diagnosis code"
    * code 1..1 string "ICD-10-GM code (e.g. C75.8)"
    * display 0..1 string "Diagnosis display text"
    * system 1..1 string "ICD-10-GM code system URI"
    * version 0..1 string "ICD-10-GM version year"
  * topography 0..1 BackboneElement "ICD-O-3 topography code"
    * code 1..1 string "Topography code"
    * display 0..1 string "Topography display"
    * system 1..1 string "Topography system URI (ICD-O-3)"
    * version 0..1 string "ICD-O-3 version"
  * grading 0..1 BackboneElement "Tumor grading history"
    * history 0..* BackboneElement "Grading history entries"
      * date 0..1 string "Grading date"
      * codes 0..* BackboneElement "Grading codes"
        * code 1..1 string "Grade code"
        * display 0..1 string "Grade display"
        * system 1..1 string "Grading system URI"
  * staging 0..1 BackboneElement "Tumor staging history"
    * history 0..* BackboneElement "Staging history entries"
      * date 0..1 string "Staging date"
      * method 0..1 BackboneElement "Staging method"
        * code 1..1 string "Method code (e.g. clinical)"
        * system 1..1 string "Method system URI"
      * tnmClassification 0..1 BackboneElement "TNM classification"
        * tumor 0..1 BackboneElement "T category"
          * code 1..1 string "T code (e.g. T0)"
          * system 1..1 string "TNM system (UICC)"
        * nodes 0..1 BackboneElement "N category"
          * code 1..1 string "N code (e.g. N2)"
          * system 1..1 string "TNM system (UICC)"
        * metastasis 0..1 BackboneElement "M category"
          * code 1..1 string "M code (e.g. M0)"
          * system 1..1 string "TNM system (UICC)"
      * otherClassifications 0..* BackboneElement "Other classification systems"
        * code 1..1 string "Classification code"
        * display 0..1 string "Classification display"
        * system 1..1 string "Classification system URI"
  * guidelineTreatmentStatus 0..1 BackboneElement "Guideline treatment exhaustion status"
    * code 1..1 string "Status code (e.g. non-exhausted)"
    * display 0..1 string "Status display"
    * system 1..1 string "Status system URI"
  * histology 0..* BackboneElement "Histology report references"
    * id 1..1 string "Histology report ID"
    * type 1..1 string "Reference type (HistologyReport)"
  * notes 0..* string "Free-text clinical notes"

// =============================================================================
// 4. familyMemberHistories
// =============================================================================
* familyMemberHistories 0..* BackboneElement "Family member cancer history entries"
  * id 1..1 string "Family member history UUID"
  * patient 1..1 BackboneElement "Patient reference"
    * id 1..1 string "Patient ID"
    * type 1..1 string "Reference type (Patient)"
  * relationship 1..1 BackboneElement "Family relationship type"
    * code 1..1 string "Relationship code"
    * display 0..1 string "Relationship display"
    * system 1..1 string "Relationship system URI"

// =============================================================================
// 5. guidelineTherapies
// =============================================================================
* guidelineTherapies 0..* BackboneElement "Guideline-based therapy entries"
  * id 1..1 string "Therapy UUID"
  * patient 1..1 BackboneElement "Patient reference"
    * id 1..1 string "Patient ID"
    * type 1..1 string "Reference type (Patient)"
  * indication 0..1 BackboneElement "Indication (MTBDiagnosis) reference"
    * id 1..1 string "Diagnosis ID"
    * type 1..1 string "Reference type (MTBDiagnosis)"
  * therapyLine 0..1 integer "Therapy line number"
  * status 0..1 BackboneElement "Therapy status"
    * code 1..1 string "Status code (e.g. stopped)"
    * display 0..1 string "Status display"
    * system 1..1 string "Status system URI"
  * statusReason 0..1 BackboneElement "Reason for therapy status"
    * code 1..1 string "Status reason code (e.g. progression)"
    * display 0..1 string "Status reason display"
    * system 1..1 string "Status reason system URI"
  * period 0..1 BackboneElement "Therapy period"
    * start 1..1 string "Start date (YYYY-MM-DD)"
    * end 0..1 string "End date (YYYY-MM-DD)"
  * medication 0..* BackboneElement "Medication codes (ATC)"
    * code 1..1 string "ATC code"
    * display 0..1 string "Medication display name"
    * system 1..1 string "ATC code system URI"
    * version 0..1 string "ATC version"
  * notes 0..* string "Free-text therapy notes"
  * category 0..1 BackboneElement "Therapy category"
    * code 1..1 string "Category code"
    * display 0..1 string "Category display"
    * system 1..1 string "Category system URI"

// =============================================================================
// 6. guidelineProcedures
// =============================================================================
* guidelineProcedures 0..* BackboneElement "Guideline-based non-medication procedures"
  * id 1..1 string "Procedure UUID"
  * patient 1..1 BackboneElement "Patient reference"
    * id 1..1 string "Patient ID"
    * type 1..1 string "Reference type (Patient)"
  * indication 0..1 BackboneElement "Indication (MTBDiagnosis) reference"
    * id 1..1 string "Diagnosis ID"
    * type 1..1 string "Reference type (MTBDiagnosis)"
  * code 1..1 BackboneElement "Procedure type code"
    * code 1..1 string "Procedure code (e.g. radiotherapy)"
    * display 0..1 string "Procedure display"
    * system 1..1 string "Procedure system URI"
  * status 0..1 BackboneElement "Procedure status"
    * code 1..1 string "Status code (e.g. ongoing)"
    * display 0..1 string "Status display"
    * system 1..1 string "Status system URI"
  * period 0..1 BackboneElement "Procedure period"
    * start 1..1 string "Start date (YYYY-MM-DD)"
    * end 0..1 string "End date (YYYY-MM-DD)"
  * intent 0..1 BackboneElement "Therapy intent"
    * code 1..1 string "Intent code (e.g. palliative)"
    * display 0..1 string "Intent display"
    * system 1..1 string "Intent system URI"
  * notes 0..* string "Free-text procedure notes"

// =============================================================================
// 7. performanceStatus
// =============================================================================
* performanceStatus 0..* BackboneElement "ECOG performance status assessments"
  * id 1..1 string "Performance status UUID"
  * patient 1..1 BackboneElement "Patient reference"
    * id 1..1 string "Patient ID"
    * type 1..1 string "Reference type (Patient)"
  * effectiveDate 1..1 string "Assessment date (YYYY-MM-DD)"
  * value 1..1 BackboneElement "ECOG score"
    * code 1..1 string "ECOG code (e.g. 0–4)"
    * display 0..1 string "ECOG display"
    * system 1..1 string "ECOG system URI"

// =============================================================================
// 8. specimens
// =============================================================================
* specimens 0..* BackboneElement "Tumor specimen entries"
  * id 1..1 string "Specimen UUID"
  * patient 1..1 BackboneElement "Patient reference"
    * id 1..1 string "Patient ID"
    * type 1..1 string "Reference type (Patient)"
  * diagnosis 0..1 BackboneElement "Associated diagnosis reference"
    * id 1..1 string "Diagnosis ID"
    * type 1..1 string "Reference type (MTBDiagnosis)"
  * type 0..1 BackboneElement "Specimen type"
    * code 1..1 string "Specimen type code (e.g. fresh-tissue)"
    * display 0..1 string "Specimen type display"
    * system 1..1 string "Specimen type system URI"
  * collection 0..1 BackboneElement "Specimen collection details"
    * date 0..1 string "Collection date (YYYY-MM-DD)"
    * site 0..1 BackboneElement "Collection site (ICD-O-3 topography)"
      * code 1..1 string "Site code"
      * display 0..1 string "Site display"
      * system 1..1 string "Site system URI"
      * version 0..1 string "ICD-O-3 version"
    * method 0..1 BackboneElement "Collection method"
      * code 1..1 string "Method code (e.g. biopsy)"
      * display 0..1 string "Method display"
      * system 1..1 string "Method system URI"

// =============================================================================
// 9. priorDiagnosticReports
// =============================================================================
* priorDiagnosticReports 0..* BackboneElement "Prior diagnostic reports (free-text)"
  * id 1..1 string "Report UUID"
  * patient 1..1 BackboneElement "Patient reference"
    * id 1..1 string "Patient ID"
    * type 1..1 string "Reference type (Patient)"
  * issuedOn 1..1 string "Report issue date (YYYY-MM-DD)"
  * results 0..* string "Free-text diagnostic result strings"

// =============================================================================
// 10. histologyReports
// =============================================================================
* histologyReports 0..* BackboneElement "Histology report entries"
  * id 1..1 string "Histology report UUID"
  * patient 1..1 BackboneElement "Patient reference"
    * id 1..1 string "Patient ID"
    * type 1..1 string "Reference type (Patient)"
  * specimen 1..1 BackboneElement "Tumor specimen reference"
    * id 1..1 string "Specimen ID"
    * type 1..1 string "Reference type (TumorSpecimen)"
  * issuedOn 1..1 string "Report issue date (YYYY-MM-DD)"
  * results 0..1 BackboneElement "Histology results"
    * tumorCellContent 0..1 BackboneElement "Histologic tumor cell content"
      * id 1..1 string "Result UUID"
      * patient 1..1 BackboneElement "Patient reference"
        * id 1..1 string "Patient ID"
        * type 1..1 string "Reference type (Patient)"
      * specimen 1..1 BackboneElement "Specimen reference"
        * id 1..1 string "Specimen ID"
        * type 1..1 string "Reference type (TumorSpecimen)"
      * method 0..1 BackboneElement "Determination method"
        * code 1..1 string "Method code (e.g. histologic)"
        * display 0..1 string "Method display"
        * system 1..1 string "Method system URI"
      * value 1..1 decimal "Tumor cell content fraction (0.0 – 1.0)"
    * tumorMorphology 0..1 BackboneElement "Tumor morphology"
      * id 1..1 string "Morphology result UUID"
      * patient 1..1 BackboneElement "Patient reference"
        * id 1..1 string "Patient ID"
        * type 1..1 string "Reference type (Patient)"
      * specimen 1..1 BackboneElement "Specimen reference"
        * id 1..1 string "Specimen ID"
        * type 1..1 string "Reference type (TumorSpecimen)"
      * morphology 0..* BackboneElement "ICD-O-3 morphology codes"
        * code 1..1 string "Morphology code"
        * display 0..1 string "Morphology display"
        * system 1..1 string "Morphology system URI (ICD-O-3)"
        * version 0..1 string "ICD-O-3 version"
      * notes 0..* string "Free-text morphology notes"

// =============================================================================
// 11. ihcReports
// =============================================================================
* ihcReports 0..* BackboneElement "Immunohistochemistry (IHC) reports"
  * id 1..1 string "IHC report UUID"
  * patient 1..1 BackboneElement "Patient reference"
    * id 1..1 string "Patient ID"
    * type 1..1 string "Reference type (Patient)"
  * specimen 1..1 BackboneElement "Tumor specimen reference"
    * id 1..1 string "Specimen ID"
    * type 1..1 string "Reference type (TumorSpecimen)"
  * issuedOn 1..1 string "Report issue date (YYYY-MM-DD)"
  * results 0..1 BackboneElement "IHC results"
    * proteinExpression 0..* BackboneElement "Protein expression results"
      * id 1..1 string "Result UUID"
      * patient 1..1 BackboneElement "Patient reference"
        * id 1..1 string "Patient ID"
        * type 1..1 string "Reference type (Patient)"
      * specimen 1..1 BackboneElement "Specimen reference"
        * id 1..1 string "Specimen ID"
        * type 1..1 string "Reference type (TumorSpecimen)"
      * protein 1..1 BackboneElement "Protein tested"
        * code 1..1 string "Protein code (e.g. BRAFP1)"
        * display 0..1 string "Protein display"
        * system 1..1 string "Protein system URI"
      * value 0..1 BackboneElement "IHC expression value"
        * code 1..1 string "Score code (e.g. 1+)"
        * display 0..1 string "Score display"
        * system 1..1 string "Score system URI"
      * tpsScore 0..1 integer "Tumor proportion score (TPS)"
      * icScore 0..1 BackboneElement "Immune-cell score"
        * code 1..1 string "IC score code"
        * display 0..1 string "IC score display"
        * system 1..1 string "IC score system URI"
      * tcScore 0..1 BackboneElement "Tumor-cell score"
        * code 1..1 string "TC score code"
        * display 0..1 string "TC score display"
        * system 1..1 string "TC score system URI"
    * msiMmr 0..* BackboneElement "MSI / MMR protein expression results"
      * id 1..1 string "Result UUID"
      * patient 1..1 BackboneElement "Patient reference"
        * id 1..1 string "Patient ID"
        * type 1..1 string "Reference type (Patient)"
      * specimen 1..1 BackboneElement "Specimen reference"
        * id 1..1 string "Specimen ID"
        * type 1..1 string "Reference type (TumorSpecimen)"
      * protein 1..1 BackboneElement "MMR protein tested (e.g. MLH1)"
        * code 1..1 string "Protein code"
        * display 0..1 string "Protein display"
        * system 1..1 string "Protein system URI"
      * value 0..1 BackboneElement "Expression result"
        * code 1..1 string "Result code (e.g. exp_present)"
        * display 0..1 string "Result display"
        * system 1..1 string "Result system URI"

// =============================================================================
// 12. msiFindings
// =============================================================================
* msiFindings 0..* BackboneElement "Microsatellite instability (MSI) findings"
  * id 1..1 string "MSI finding UUID"
  * patient 1..1 BackboneElement "Patient reference"
    * id 1..1 string "Patient ID"
    * type 1..1 string "Reference type (Patient)"
  * specimen 1..1 BackboneElement "Tumor specimen reference"
    * id 1..1 string "Specimen ID"
    * type 1..1 string "Reference type (TumorSpecimen)"
  * ngsReport 0..1 BackboneElement "Associated NGS report reference"
    * id 1..1 string "NGS report ID"
    * type 1..1 string "Reference type (NGSReport)"
  * issuedOn 1..1 string "Finding date (YYYY-MM-DD)"
  * value 1..1 BackboneElement "MSI result value"
    * code 1..1 string "MSI code (e.g. MSI-H)"
    * display 0..1 string "MSI display"
    * system 1..1 string "MSI system URI"
  * method 0..1 BackboneElement "MSI determination method"
    * code 1..1 string "Method code (e.g. bioinformatics)"
    * display 0..1 string "Method display"
    * system 1..1 string "Method system URI"

// =============================================================================
// 13. ngsReports
// (Full inline definition; canonical definition in dnpm-lm-ngs-report.fsh)
// =============================================================================
* ngsReports 0..* BackboneElement "NGS sequencing reports"
  * id 1..1 string "NGS Report UUID"
  * patient 1..1 BackboneElement "Patient reference"
    * id 1..1 string "Patient ID"
    * type 1..1 string "Reference type (Patient)"
  * specimen 1..1 BackboneElement "Tumor specimen reference"
    * id 1..1 string "Specimen ID"
    * type 1..1 string "Reference type (TumorSpecimen)"
  * issuedOn 1..1 string "Report issue date (YYYY-MM-DD)"
  * type 1..1 BackboneElement "NGS analysis type"
    * code 1..1 string "Type code (e.g. exome)"
    * display 0..1 string "Type display"
    * system 1..1 string "Type system URI"
  * metadata 0..1 BackboneElement "NGS run metadata"
    * referenceGenome 0..1 BackboneElement "Reference genome"
      * code 1..1 string "Genome build (e.g. GRCh38)"
      * display 0..1 string "Genome build display"
      * system 1..1 string "Genome build system URI"
    * sequencer 0..1 BackboneElement "Sequencer instrument"
      * code 1..1 string "Sequencer code"
      * display 0..1 string "Sequencer display"
      * system 1..1 string "Sequencer system URI"
    * kitManufacturer 0..1 string "Kit manufacturer"
    * kitType 0..1 string "Kit type"
    * pipeline 0..1 string "Bioinformatics pipeline"
    * tumorCellContent 0..1 BackboneElement "Pre-sequencing tumor cell content estimate"
      * method 0..1 BackboneElement "Estimation method"
        * code 1..1 string "Method code"
        * display 0..1 string "Method display"
        * system 1..1 string "Method system URI"
      * value 1..1 decimal "Fraction (0.0 – 1.0)"
  * results 1..1 BackboneElement "NGS analysis results"
    * tumorCellContent 0..1 BackboneElement "Bioinformatic tumor cell content"
      * id 1..1 string "Result UUID"
      * patient 1..1 BackboneElement "Patient reference"
        * id 1..1 string "Patient ID"
        * type 1..1 string "Reference type"
      * specimen 1..1 BackboneElement "Specimen reference"
        * id 1..1 string "Specimen ID"
        * type 1..1 string "Reference type"
      * method 1..1 BackboneElement "Determination method"
        * code 1..1 string "Method code (e.g. bioinformatic)"
        * display 0..1 string "Method display"
        * system 1..1 string "Method system URI"
      * value 1..1 decimal "Fraction (0.0 – 1.0)"
    * tmb 0..1 BackboneElement "Tumor Mutational Burden"
      * id 1..1 string "TMB result UUID"
      * patient 1..1 BackboneElement "Patient reference"
        * id 1..1 string "Patient ID"
        * type 1..1 string "Reference type"
      * specimen 1..1 BackboneElement "Specimen reference"
        * id 1..1 string "Specimen ID"
        * type 1..1 string "Reference type"
      * value 1..1 BackboneElement "TMB quantity"
        * value 1..1 decimal "Numeric value"
        * unit 1..1 string "Unit"
      * interpretation 0..1 BackboneElement "TMB interpretation"
        * code 1..1 string "Code (e.g. high)"
        * display 0..1 string "Display"
        * system 1..1 string "System URI"
    * brcaness 0..1 BackboneElement "BRCAness score"
      * id 1..1 string "BRCAness result UUID"
      * patient 1..1 BackboneElement "Patient reference"
        * id 1..1 string "Patient ID"
        * type 1..1 string "Reference type"
      * specimen 1..1 BackboneElement "Specimen reference"
        * id 1..1 string "Specimen ID"
        * type 1..1 string "Reference type"
      * value 1..1 decimal "BRCAness score (0.0 – 1.0)"
      * confidenceRange 0..1 BackboneElement "Confidence range"
        * min 1..1 decimal "Minimum"
        * max 1..1 decimal "Maximum"
    * hrdScore 0..1 BackboneElement "HRD Score"
      * id 1..1 string "HRD result UUID"
      * patient 1..1 BackboneElement "Patient reference"
        * id 1..1 string "Patient ID"
        * type 1..1 string "Reference type"
      * specimen 1..1 BackboneElement "Specimen reference"
        * id 1..1 string "Specimen ID"
        * type 1..1 string "Reference type"
      * value 1..1 decimal "HRD composite score"
      * components 0..1 BackboneElement "HRD component scores"
        * lst 0..1 decimal "LST score"
        * loh 0..1 decimal "LOH score"
        * tai 0..1 decimal "TAI score"
      * interpretation 0..1 BackboneElement "HRD interpretation"
        * code 1..1 string "Code (e.g. low)"
        * display 0..1 string "Display"
        * system 1..1 string "System URI"
    * simpleVariants 0..* BackboneElement "Simple variants (SNV / small indels)"
      * id 1..1 string "Variant UUID"
      * patient 1..1 BackboneElement "Patient reference"
        * id 1..1 string "Patient ID"
        * type 1..1 string "Reference type"
      * externalIds 0..* BackboneElement "External identifiers (e.g. dbSNP)"
        * value 1..1 string "Identifier value"
        * system 1..1 string "Identifier system URI"
      * chromosome 1..1 string "Chromosome (e.g. chr4)"
      * gene 1..1 BackboneElement "Affected gene"
        * code 1..1 string "HGNC gene code"
        * display 0..1 string "Gene symbol"
        * system 1..1 string "Gene nomenclature system URI"
      * localization 0..* BackboneElement "Variant localization in gene"
        * code 1..1 string "Localization code"
        * display 0..1 string "Localization display"
        * system 1..1 string "Localization system URI"
      * transcriptId 0..1 BackboneElement "Transcript identifier"
        * value 1..1 string "Transcript ID (e.g. ENST...)"
        * system 1..1 string "Transcript system URI"
      * exonId 0..1 string "Exon identifier"
      * position 0..1 BackboneElement "Genomic position"
        * start 1..1 integer "Start position"
        * end 0..1 integer "End position"
      * altAllele 1..1 string "Alternate allele"
      * refAllele 1..1 string "Reference allele"
      * dnaChange 0..1 string "cDNA change (HGVS)"
      * proteinChange 0..1 string "Protein change (HGVS)"
      * readDepth 0..1 integer "Read depth"
      * allelicFrequency 0..1 decimal "Allelic frequency"
      * interpretation 0..1 BackboneElement "ClinVar interpretation"
        * code 1..1 string "Interpretation code"
        * display 0..1 string "Interpretation display"
        * system 1..1 string "Interpretation system URI"
    * copyNumberVariants 0..* BackboneElement "Copy number variants"
      * id 1..1 string "CNV UUID"
      * patient 1..1 BackboneElement "Patient reference"
        * id 1..1 string "Patient ID"
        * type 1..1 string "Reference type"
      * chromosome 1..1 string "Chromosome (e.g. chr7)"
      * localization 0..* BackboneElement "CNV localization"
        * code 1..1 string "Localization code"
        * display 0..1 string "Localization display"
        * system 1..1 string "Localization system URI"
      * startRange 0..1 BackboneElement "Start position range"
        * start 1..1 integer "Range start"
        * end 1..1 integer "Range end"
      * endRange 0..1 BackboneElement "End position range"
        * start 1..1 integer "Range start"
        * end 1..1 integer "Range end"
      * totalCopyNumber 0..1 integer "Total copy number"
      * relativeCopyNumber 0..1 decimal "Relative copy number"
      * cnA 0..1 integer "Copy number allele A"
      * cnB 0..1 integer "Copy number allele B"
      * reportedAffectedGenes 0..* BackboneElement "Affected genes"
        * code 1..1 string "HGNC gene code"
        * display 0..1 string "Gene symbol"
        * system 1..1 string "Gene nomenclature system URI"
      * focality 0..1 BackboneElement "CNV focality"
        * code 1..1 string "Focality code (e.g. focal)"
        * display 0..1 string "Focality display"
        * system 1..1 string "Focality system URI"
      * type 1..1 BackboneElement "CNV type"
        * code 1..1 string "CNV type code (e.g. gain)"
        * display 0..1 string "CNV type display"
        * system 1..1 string "CNV type system URI"
    * dnaFusions 0..* BackboneElement "DNA-level gene fusions"
      * id 1..1 string "DNA fusion UUID"
      * patient 1..1 BackboneElement "Patient reference"
        * id 1..1 string "Patient ID"
        * type 1..1 string "Reference type"
      * localization 0..* BackboneElement "Fusion localization"
        * code 1..1 string "Localization code"
        * display 0..1 string "Localization display"
        * system 1..1 string "Localization system URI"
      * fusionPartner5prime 0..1 BackboneElement "5-prime fusion partner"
        * gene 1..1 BackboneElement "5-prime partner gene"
          * code 1..1 string "HGNC gene code"
          * display 0..1 string "Gene symbol"
          * system 1..1 string "Gene nomenclature system URI"
        * position 1..1 integer "Breakpoint position"
      * fusionPartner3prime 0..1 BackboneElement "3-prime fusion partner"
        * gene 1..1 BackboneElement "3-prime partner gene"
          * code 1..1 string "HGNC gene code"
          * display 0..1 string "Gene symbol"
          * system 1..1 string "Gene nomenclature system URI"
        * position 1..1 integer "Breakpoint position"
      * reportedNumReads 0..1 integer "Supporting read count"
    * rnaFusions 0..* BackboneElement "RNA-level gene fusions"
      * id 1..1 string "RNA fusion UUID"
      * patient 1..1 BackboneElement "Patient reference"
        * id 1..1 string "Patient ID"
        * type 1..1 string "Reference type"
      * externalIds 0..* BackboneElement "External identifiers (e.g. COSMIC)"
        * value 1..1 string "Identifier value"
        * system 1..1 string "Identifier system URI"
      * localization 0..* BackboneElement "Fusion localization"
        * code 1..1 string "Localization code"
        * display 0..1 string "Localization display"
        * system 1..1 string "Localization system URI"
      * fusionPartner5prime 0..1 BackboneElement "5-prime fusion partner"
        * gene 1..1 BackboneElement "5-prime partner gene"
          * code 1..1 string "HGNC gene code"
          * display 0..1 string "Gene symbol"
          * system 1..1 string "Gene nomenclature system URI"
        * transcript 0..1 BackboneElement "5-prime transcript"
          * value 1..1 string "Transcript ID (e.g. ENST...)"
          * system 1..1 string "Transcript system URI"
        * exon 0..1 string "Exon identifier"
        * position 1..1 integer "Breakpoint position"
        * strand 0..1 string "Strand (+ or -)"
      * fusionPartner3prime 0..1 BackboneElement "3-prime fusion partner"
        * gene 1..1 BackboneElement "3-prime partner gene"
          * code 1..1 string "HGNC gene code"
          * display 0..1 string "Gene symbol"
          * system 1..1 string "Gene nomenclature system URI"
        * transcript 0..1 BackboneElement "3-prime transcript"
          * value 1..1 string "Transcript ID (e.g. ENST...)"
          * system 1..1 string "Transcript system URI"
        * exon 0..1 string "Exon identifier"
        * position 1..1 integer "Breakpoint position"
        * strand 0..1 string "Strand (+ or -)"
      * effect 0..1 BackboneElement "RNA fusion effect"
        * code 1..1 string "Effect code (e.g. in-frame)"
        * display 0..1 string "Effect display"
        * system 1..1 string "Effect system URI"
      * reportedNumReads 0..1 integer "Supporting read count"

// =============================================================================
// 14. carePlans
// (Full inline definition; canonical definition in dnpm-lm-care-plan.fsh)
// =============================================================================
* carePlans 0..* BackboneElement "MTB care plans"
  * id 1..1 string "Care plan UUID"
  * patient 1..1 BackboneElement "Patient reference"
    * id 1..1 string "Patient ID"
    * type 1..1 string "Reference type (Patient)"
  * issuedOn 1..1 string "Issue date (YYYY-MM-DD)"
  * reason 0..1 BackboneElement "Indication (MTBDiagnosis) reference"
    * id 1..1 string "Diagnosis ID"
    * type 1..1 string "Reference type (MTBDiagnosis)"
  * noTargetFinding 0..1 boolean "True when no actionable target was found"
  * geneticCounselingRecommendation 0..1 BackboneElement "Genetic counselling recommendation"
    * id 1..1 string "Recommendation UUID"
    * patient 1..1 BackboneElement "Patient reference"
      * id 1..1 string "Patient ID"
      * type 1..1 string "Reference type (Patient)"
    * issuedOn 1..1 string "Recommendation date (YYYY-MM-DD)"
    * reason 0..1 BackboneElement "Counselling reason"
      * code 1..1 string "Reason code"
      * display 0..1 string "Reason display"
      * system 1..1 string "Reason system URI"
  * medicationRecommendations 0..* BackboneElement "Medication therapy recommendations"
    * id 1..1 string "Recommendation UUID"
    * patient 1..1 BackboneElement "Patient reference"
      * id 1..1 string "Patient ID"
      * type 1..1 string "Reference type (Patient)"
    * issuedOn 1..1 string "Recommendation date (YYYY-MM-DD)"
    * indication 0..1 BackboneElement "Indication reference"
      * id 1..1 string "Diagnosis ID"
      * type 1..1 string "Reference type (MTBDiagnosis)"
    * priority 0..1 BackboneElement "Recommendation priority"
      * code 1..1 string "Priority code (e.g. 1)"
      * display 0..1 string "Priority display"
      * system 1..1 string "Priority system URI"
    * medication 0..* BackboneElement "Recommended medications (ATC)"
      * code 1..1 string "ATC code"
      * display 0..1 string "Medication display"
      * system 1..1 string "ATC system URI"
      * version 0..1 string "ATC version"
    * supportingVariants 0..* BackboneElement "Supporting variants"
      * id 1..1 string "Variant ID"
      * type 1..1 string "Variant type (SNV | CNV | DNAFusion | RNAFusion)"
    * levelOfEvidence 0..1 BackboneElement "Level of evidence"
      * grading 0..1 BackboneElement "Evidence grading"
        * code 1..1 string "Grade code (e.g. m1A)"
        * display 0..1 string "Grade display"
        * system 1..1 string "Grade system URI"
      * addendums 0..* BackboneElement "Evidence addendums"
        * code 1..1 string "Addendum code"
        * display 0..1 string "Addendum display"
        * system 1..1 string "Addendum system URI"
      * publications 0..* BackboneElement "Supporting publications"
        * pmid 0..1 string "PubMed ID"
        * doi 0..1 string "Digital Object Identifier"
  * studyEnrollmentRecommendations 0..* BackboneElement "Study enrollment recommendations"
    * id 1..1 string "Recommendation UUID"
    * patient 1..1 BackboneElement "Patient reference"
      * id 1..1 string "Patient ID"
      * type 1..1 string "Reference type (Patient)"
    * issuedOn 1..1 string "Recommendation date (YYYY-MM-DD)"
    * indication 0..1 BackboneElement "Indication reference"
      * id 1..1 string "Diagnosis ID"
      * type 1..1 string "Reference type (MTBDiagnosis)"
    * supportingVariants 0..* BackboneElement "Supporting variants"
      * id 1..1 string "Variant ID"
      * type 1..1 string "Variant type"
    * studies 0..* BackboneElement "Recommended studies"
      * id 1..1 string "Study ID (e.g. NCT number)"
      * system 1..1 string "Study registry system URI"

// =============================================================================
// 15. followUps
// =============================================================================
* followUps 0..* BackboneElement "Follow-up visit entries"
  * id 1..1 string "Follow-up UUID"
  * patient 1..1 BackboneElement "Patient reference"
    * id 1..1 string "Patient ID"
    * type 1..1 string "Reference type (Patient)"
  * date 1..1 string "Follow-up date (YYYY-MM-DD)"
  * lastContactDate 0..1 string "Date of last patient contact (YYYY-MM-DD)"
  * patientStatus 0..1 BackboneElement "Patient status at follow-up"
    * code 1..1 string "Status code (e.g. alive)"
    * display 0..1 string "Status display"
    * system 1..1 string "Status system URI"
  * claims 0..* BackboneElement "Claim references at follow-up"
    * id 1..1 string "Claim ID"
    * type 1..1 string "Reference type (Claim)"
  * therapyChanged 0..1 boolean "Whether therapy was changed at this follow-up"

// =============================================================================
// 16. claims
// =============================================================================
* claims 0..* BackboneElement "Insurance / cost coverage claim entries"
  * id 1..1 string "Claim UUID"
  * patient 1..1 BackboneElement "Patient reference"
    * id 1..1 string "Patient ID"
    * type 1..1 string "Reference type (Patient)"
  * recommendation 1..1 BackboneElement "Associated medication recommendation reference"
    * id 1..1 string "Recommendation ID"
    * type 1..1 string "Reference type (MTBMedicationRecommendation)"
  * issuedOn 1..1 string "Claim issue date (YYYY-MM-DD)"

// =============================================================================
// 17. claimResponses
// =============================================================================
* claimResponses 0..* BackboneElement "Insurance / cost coverage claim response entries"
  * id 1..1 string "Claim response UUID"
  * patient 1..1 BackboneElement "Patient reference"
    * id 1..1 string "Patient ID"
    * type 1..1 string "Reference type (Patient)"
  * claim 1..1 BackboneElement "Associated claim reference"
    * id 1..1 string "Claim ID"
    * type 1..1 string "Reference type (Claim)"
  * issuedOn 1..1 string "Response date (YYYY-MM-DD)"
  * status 1..1 BackboneElement "Response status"
    * code 1..1 string "Status code (e.g. rejected)"
    * display 0..1 string "Status display"
    * system 1..1 string "Status system URI"
  * statusReason 0..1 BackboneElement "Reason for response status"
    * code 1..1 string "Reason code"
    * display 0..1 string "Reason display"
    * system 1..1 string "Reason system URI"

// =============================================================================
// 18. systemicTherapies
// Note: each array element wraps a `history` array; actual therapy data is in
// history[]. This two-level structure reflects the DNPM API design.
// =============================================================================
* systemicTherapies 0..* BackboneElement "Systemic (molecular) therapy entries (each wraps a history)"
  * history 0..* BackboneElement "Therapy version history entries"
    * id 1..1 string "Therapy entry UUID"
    * patient 1..1 BackboneElement "Patient reference"
      * id 1..1 string "Patient ID"
      * type 1..1 string "Reference type (Patient)"
    * indication 0..1 BackboneElement "Indication reference"
      * id 1..1 string "Diagnosis ID"
      * type 1..1 string "Reference type (MTBDiagnosis)"
    * basedOn 0..1 BackboneElement "Medication recommendation reference"
      * id 1..1 string "Recommendation ID"
      * type 1..1 string "Reference type (MTBMedicationRecommendation)"
    * therapyLine 0..1 integer "Therapy line number"
    * status 0..1 BackboneElement "Therapy status"
      * code 1..1 string "Status code (e.g. completed)"
      * display 0..1 string "Status display"
      * system 1..1 string "Status system URI"
    * statusReason 0..1 BackboneElement "Reason for therapy status"
      * code 1..1 string "Status reason code"
      * display 0..1 string "Status reason display"
      * system 1..1 string "Status reason system URI"
    * period 0..1 BackboneElement "Therapy period"
      * start 1..1 string "Start date (YYYY-MM-DD)"
      * end 0..1 string "End date (YYYY-MM-DD)"
    * medication 0..* BackboneElement "Medication codes (ATC)"
      * code 1..1 string "ATC code"
      * display 0..1 string "Medication display"
      * system 1..1 string "ATC system URI"
      * version 0..1 string "ATC version"
    * notes 0..* string "Free-text therapy notes"

// =============================================================================
// 19. responses
// =============================================================================
* responses 0..* BackboneElement "Therapy response assessments"
  * id 1..1 string "Response UUID"
  * patient 1..1 BackboneElement "Patient reference"
    * id 1..1 string "Patient ID"
    * type 1..1 string "Reference type (Patient)"
  * therapy 1..1 BackboneElement "Associated systemic therapy reference"
    * id 1..1 string "Therapy ID"
    * type 1..1 string "Reference type (MTBSystemicTherapy)"
  * effectiveDate 1..1 string "Response assessment date (YYYY-MM-DD)"
  * value 1..1 BackboneElement "RECIST response category"
    * code 1..1 string "RECIST code (e.g. SD, PR, CR, PD)"
    * display 0..1 string "RECIST display (e.g. Stable Disease)"
    * system 1..1 string "RECIST system (e.g. RECIST)"
