RuleSet: Vortherapie
* Vortherapie             0..*      BackboneElement       "Vortherapie"
  * Kategorie             0..1      code                  "Kategorie"                 "Kategorie der Leitlinientherapie (Prozedur)"
  * Startdatum            1..1      dateTime              "Startdatum"                "Startdatum der Vortherapie"
  * Enddatum              0..1      dateTime              "Enddatum"                  "Enddatum der Vortherapie"
  * Diagnose              0..*      Reference(Condition)  "Verweis auf Diagnose"      "Verweis auf i.d.R. die Anmeldediagnose, in seltenen Fällen weitere Diagnosen"
  * Therapiestatusgrund   0..1      code                  "Therapiestatusgrund"       "Gibt den Grund an, warum die Systemtherapie beendet wurde"
  * Therapieplan          0..1      Reference(CarePlan)   "Verweis auf Therapieplan"  "Verweis auf den im Molekularen Tumorboard beschlossenen Therapieplan"
  * Therapielinie         0..1      unsignedInt           "Therapielinie"             "Therapielinie der Vortherapie (0 bis 9)"
  * Zulassungsstatus      0..1      code                  "Zulassungsstatus"          "Zulassungsstatus der Vortherapie"

RuleSet: VortherapieMapping
* Vortherapie             ->  "Procedure"
  * Kategorie             ->  "Procedure.category"
  * Startdatum            ->  "Procedure.performedPeriod.start"
  * Enddatum              ->  "Procedure.performedPeriod.end"
  * Diagnose              ->  "Procedure.reasonReference:Reference(Condition)"
  * Therapiestatusgrund   ->  "Procedure.statusReason"
  * Therapieplan          ->  "Procedure.basedOn"
  * Therapielinie         ->  "Procedure.extension.extension(Therapielinie)"
  * Zulassungsstatus      ->  "Procedure.extension.extension(Zulassungsstatus)"