RuleSet: Vortherapie
* Vortherapie            1..*      BackboneElement      "Vortherapie"
  * Diagnose             0..*      Reference(Condition) "Verweis auf Diagnose"   "Verweis auf i.d.R. die Anmeldediagnose, in seltenen Fällen weitere Diagnosen"
  * Zulassungsstatus     0..1      code                 "Zulassungsstatus"       "Zulassungsstatus der Vortherapie"
  * Therapielinie        0..1      unsignedInt          "Therapielinie"          "Therapielinie der Vortherapie (0 bis 9)"
  * Startdatum           0..1      dateTime             "Startdatum"             "Startdatum der Vortherapie"
  * Enddatum             0..1      dateTime             "Enddatum"               "Enddatum der Vortherapie"
  * Wirkstoffe           0..*      code                 "Wirkstoffe"             "Wirkstoffe der systemischen Leitlinientherapie"
  * Therapiestatusgrund        0..1      code                 "Therapiestatusgrund"          "Gibt den Grund an, warum die Systemtherapie beendet wurde"
  * Kategorie            0..1      code                 "Kategorie"              "Kategorie der Leitlinientherapie (Prozedur)"

RuleSet: VortherapieMapping
* Vortherapie         -> "Procedure"
  * Diagnose          -> "Procedure.reasonReference:Reference(Condition)"
  * Zulassungsstatus  -> "ClinicalImpression.extension.extension(Zulassungsstatus)"
  * Therapielinie     -> "ClinicalImpression.extension.extension(Therapielinie)"
  * Startdatum        -> "Procedure.performedPeriod.start"
  * Enddatum          -> "Procedure.performedPeriod.end"
  * Wirkstoffe        -> "MedicationStatement.medicationCodeableConcept"
  * Therapiestatusgrund     -> "Procedure.outcome.coding.code"
  * Kategorie         -> "Procedure.category"