name: IG Publisher

on:
  push:
    branches:
      - main
      - dev
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-ig:
    name: Build Profiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get FHIR packages
        uses: cybernop/fill-fhir-cache@v1
      - name: Build profiles
        uses: cybernop/build-fhir-ig@v1
        with:
          sushi-version: "3.0.0-beta.2"
      - name: Archive profile artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: output/package.tgz
      - name: Archive generated pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: output

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build-ig
    if: github.ref_name == 'dev'
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
